# Generated by Django 3.2.10 on 2022-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('0', 'Riobamba'), ('1', 'Quito'), ('2', 'Guayaquil'), ('3', 'Ambato'), ('4', 'Cuenca')], max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Teléfono'),
        ),
    ]
