# Generated by Django 3.2.10 on 2022-02-03 04:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comment_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
