# Generated by Django 3.2.10 on 2022-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1_opt_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2_opt_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3_opt_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_4_opt_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto alt. 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image_opt_text',
            field=models.CharField(max_length=50, verbose_name='Texto alt. Principal'),
        ),
    ]
