# Generated by Django 3.2.10 on 2022-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220121_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='articles/optional', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_1_opt_text',
            field=models.CharField(blank=True, default='Sin descripción', max_length=50, null=True, verbose_name='Texto alt. 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='articles/optional', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2_opt_text',
            field=models.CharField(blank=True, default='Sin descripción', max_length=50, null=True, verbose_name='Texto alt. 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='articles/optional', verbose_name='Imagen 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3_opt_text',
            field=models.CharField(blank=True, default='Sin descripción', max_length=50, null=True, verbose_name='Texto alt. 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_4',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='articles/optional', verbose_name='Imagen 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_4_opt_text',
            field=models.CharField(blank=True, default='Sin descripción', max_length=50, null=True, verbose_name='Texto alt. 5'),
        ),
    ]
